# Generated by Django 2.2.2 on 2019-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingform',
            name='posting_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
