# Generated by Django 2.2.2 on 2019-07-04 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_postingform_posting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Account'),
        ),
        migrations.AlterField(
            model_name='postingform',
            name='posting_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.Account'),
        ),
    ]
