# Generated by Django 2.2.2 on 2019-07-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20190704_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_of_posting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting.PostingForm'),
        ),
    ]
