# Generated by Django 2.2.2 on 2019-07-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20190711_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postingform',
            name='posting_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_of_posting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posting.PostingForm'),
        ),
    ]
