# Generated by Django 2.2.2 on 2019-07-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_image',
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
